### ISSUE TITLE
Duplicated gene_id in merged expression matrices

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/d3b-bixu-data-assembly#12]
To be discussed in the next toolkit meeting. 

Using the latest merged TPM/Count expression matrices from data assembly project:

1. `gene_id` column is duplicated

```
# TPM matrix
tpm <- readRDS('~/Downloads/gene-expression-rsem-tpm.BS_MADCWWMX.rds')
grep('gene_id', colnames(tpm))
[1]    1 2527
```

This is also the case with counts matrix

cc: @aadamk

**Comment by zhangb1** [comment]
Thanks to Komal, this has been fixed: https://github.com/d3b-center/d3b-bixu-data-assembly/blob/cwl_toolkits_update/scripts/merge_rsem/combine-matrices.R

I tested loacally no duplicate now. will be fixed in cwl .

**Comment by komalsrathi** [comment]
Closing as this seems resolved.
