### ISSUE TITLE
Incomplete PNOC008 clinical data in data assembly histologies

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/d3b-bixu-data-assembly#13]
Some issues that we should look into to ensure PNOC008 sample information is correctly filled in the data assembly histologies file:

1) Histology information is missing from data assembly file. For this issue, the KF clinical file is also not helpful as it has a lot of missing information. Should we try to manually fill this information? 

```
# columns relevant to generalized patient reporting
hist_cols_used <- c("Kids_First_Biospecimen_ID","sample_id","cohort","cohort_participant_id",
                    "parent_aliquot_id","aliquot_id",
                    "experimental_strategy","RNA_library",
                    "sample_type","tumor_descriptor",
                    "pathology_diagnosis","integrated_diagnosis",
                    "short_histology","broad_histology","molecular_subtype",
                    "gtex_group","cancer_group",
                    "OS_days","OS_status")

# read most recent data assembly and keep only columns relevant to generalized patient reporting
data_assembly <- read.delim('~/Downloads/histologies-add-bixops-uptoPNOC008-52.tsv')
data_assembly <- data_assembly %>%
  filter(cohort %in% c("PNOC", "CBTN")) %>%
  mutate(parent_aliquot_id = NA,
         gtex_group = NA, 
         cancer_group = NA) %>%
  dplyr::select(hist_cols_used) # 3687 rows

# read PNOC008 clinical manifest from KF data tracker
pnoc008_clinical <- readxl::read_xlsx('~/Projects/OMPARE/data/manifest/pnoc008_manifest.xlsx')

# integrated_diagnosis, short_histology, broad_histology, molecular_subtype missing entirely
data_assembly %>%
  dplyr::filter(cohort_participant_id %in% pnoc008_clinical$`Research ID`) %>%
  dplyr::select(integrated_diagnosis, short_histology, broad_histology, molecular_subtype) %>% 
  unique()

  integrated_diagnosis short_histology broad_histology molecular_subtype
1                   NA            <NA>            <NA>              <NA>
```

2) Missing survival information:

```
# combine PNOC008 clinical with data assembly on common cohort participant identifiers
pnoc008_clinical %>%
  dplyr::select(`Research ID`, `Last Known Status`, `Age at Diagnosis (in days)`, `Age at Collection (in days)`, `Age at Age At Last Known Status (if deceased, this is days to death)`, ) %>%
  inner_join(data_assembly %>%
               dplyr::select(cohort_participant_id, OS_status, OS_days) %>%
               unique(), by = c("Research ID" = "cohort_participant_id"))
```

First four columns are from KF clinical file and last two from data assembly file:

Research   ID | Last Known Status | Age at Diagnosis (in days) | Age at Collection (in days) | Age at Age At Last Known Status   (if deceased, this is days to death) | OS_status | OS_days
-- | -- | -- | -- | -- | -- | --
C3064299 | Living | 4065 | 4067 | NA | NA | NA
C3064422 | Deceased | 2758 | 2758 | 3074 | NA | NA
C3070818 | Living | 737 | 737 | NA | NA | NA
C3070941 | Living | 4143 | 4143 | NA | NA | NA
C3071064 | Living | 6784 | 6784 | NA | NA | NA
C3071310 | Living | 3922 | 3922 | NA | NA | NA
C3071433 | Living | NA | NA | NA | NA | NA
C3077337 | Living | 5151 | 5151 | NA | NA | NA
C3077460 | Living | 2288 | 2288 | NA | NA | NA
C3077583 | Living | 4049 | 4049 | NA | NA | NA
C3077706 | Living | 5233 | 5233 | NA | NA | NA
C3077829 | Living | 7309 | NA | NA | NA | NA
C3078075 | Living | 3480 | 3480 | NA | NA | NA
C3077952 | Living | 2801 | 2801 | NA | NA | NA
C3078198 | Living | 3147 | 3147 | NA | NA | NA
C3183978 | Living | NA | 2435 | NA | NA | NA
C3172416 | Living | NA | 1552 | NA | NA | NA
C3172539 | Living | NA | 5688 | NA | NA | NA
C3172662 | Living | NA | 4867 | NA | NA | NA
C3172785 | Living | NA | 6904 | NA | NA | NA
C3172908 | Living | NA | 3072 | NA | NA | NA
C3173031 | Living | NA | 5080 | NA | NA | NA
C3173154 | Living | NA | 3863 | NA | NA | NA
C3173277 | Living | NA | 5353 | NA | NA | NA
C3173400 | Living | NA | 1886 | NA | NA | NA
C3173523 | Living | NA | 1825 | NA | NA | NA
C3173646 | Living | NA | 4532 | NA | NA | NA
C3173769 | Living | NA | 2038 | NA | NA | NA
C3505500 | Living | NA | 4715 | NA | NA | NA
C3505623 | Living | NA | 1065 | NA | NA | NA
C3505746 | Living | NA | 3376 | NA | NA | NA
C3505869 | Living | NA | 6783 | NA | NA | NA
C3505992 | Living | NA | 1991 | NA | NA | NA
C3506115 | Living | NA | 5569 | NA | NA | NA
C3506238 | Living | NA | 1765 | NA | NA | NA
C3506361 | Living | NA | 1126 | NA | NA | NA
C3506484 | Living | NA | 2952 | NA | NA | NA
C3506607 | Living | NA | 6026 | NA | NA | NA
C3506730 | Living | NA | 4687 | NA | NA | NA
C3506853 | Living | NA | 5874 | NA | NA | NA
C3506976 | Living | NA | 4352 | NA | NA | NA
C3507099 | Living | NA | 4015 | NA | NA | NA
C3507222 | Living | NA | 4991 | NA | NA | NA
C3507345 | Living | NA | 6300 | NA | NA | NA
C3507468 | Living | NA | 6817 | NA | NA | NA
C3507714 | Living | NA | 2069 | NA | NA | NA
C3507591 | Living | NA | 4869 | NA | NA | NA
C3507837 | Living | NA | 4595 | NA | NA | NA
C3507960 | Living | NA | 4169 | NA | NA | NA
C3508083 | Living | NA | 3165 | NA | NA | NA

cc: @aadamk

**Comment by komalsrathi** [comment]
@zhangb1 Just putting these here so we can discuss in the toolkit meeting on how to best incorporate the missing information.

**Comment by jharenza** [comment]
Following

**Comment by komalsrathi** [comment]
Closing as this does not seem to be an issue any more.
