### ISSUE TITLE
Collapse and combine GTEx TPM and expected_count to KFDRC collapsed RSEM files

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/d3b-bixu-data-assembly#7]
## Background:
For OT we will need each data release to included  processed GTEx v8 data in `gene-expression-rsem-tpm-collapsed.rds` and `gene-counts-rsem-expected_count-collapsed.rds`. 

In the last data release I did:
- [script](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/gtex-rename/analyses/collapse-rnaseq/00-collapse_matrices.R) to collapse GTEx  and not removing the genes that are not expressed ie have rowSum ==0 
      output `gtex-gene-expression-rsem-tpm-collapsed.rds`
- [script](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/gtex-rename/analyses/collapse-rnaseq/00-collapse_matrices.R) to collapse PBTA+GMFK merge rsem file and not removing the genes that are not expressed ie have rowSum ==0 
     output `pbta-gmkf-gene-expression-rsem-tpm-collapsed.rds`
- [notebook](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/gtex-rename/analyses/collapse-rnaseq/gtex_pbta_gmkf_merge.Rmd) to combine the two file 
     output  `gene-expression-rsem-tpm-collapsed.rds`

## Required update
Update the [collapse-rnaseq](https://github.com/d3b-center/d3b-bixu-data-assembly/blob/master/scripts/collapse-rnaseq) to be able to handle adding GTEx processed files.

- GTEx v8 processed files can be downloaded from:
TPM https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz
expected_count https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz
- keep genes with rowSum ==0
- combine file filtering for common genes

CC @zhangb1 @yuankunzhu @jharenza  for discussion.

**Comment by jharenza** [comment]
@zhangb1 do you have an eta for this ticket?

**Comment by zhangb1** [comment]
@jharenza  can someone from your team take care of the ticket, maybe run? 

I really need to focus on the data assembly cwl develop this week.

**Comment by jharenza** [comment]
I don't think she has ec2 access yet and we have a lot of open issues for OT that need to be done as well - @yuankunzhu can someone else help with these upstream processes?

**Comment by zhangb1** [comment]
Trying to run locally but have the memory issue. can't process 

I need to wrap the cwl and try to run on cavatica project. 

the error

```
➜  GTEx Rscript 00-collapse_matrices.R -i gene-expression-rsem-tpm.rds -g gencode.v27.primary_assembly.annotation.gtf.gz -m gene-expression-rsem-tpm-collapsed.rds -t gene-expression-rsem-tpm-collapsed_table.rds -n GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz
[1] "Generating input matrix and drops table...!"
[1] "Read merged GTEx data"

── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  .default = col_double(),
  Name = col_character(),
  Description = col_character()
)
ℹ Use `spec()` for the full column specifications.



[1]    95949 killed     Rscript 00-collapse_matrices.R -i gene-expression-rsem-tpm.rds -g  -m  -t  -n
```

**Comment by kgaonkar6** [comment]
I had to run it on a large EC2, GTEx files are huge

**Comment by zhangb1** [comment]
I ran the gtex collapsed data  on cavatica project 
here: https://cavatica.sbgenomics.com/u/zhangb1/test-download/tasks/2d842fee-65cf-4c5b-b1aa-0e458b2dfa29/

and I ran the `pbta-gmkf-gene-expression-rsem-tpm-collapsed.rds` locally. 

when I tried to merge the files using the notebook. 

```
> common_genes <- intersect(rownames(gtex),rownames(pbta_gmkf))
> length(common_genes)
[1] 0
```

the length of the common_genes is 0. 

@kgaonkar6 can you take a look?

**Comment by zhangb1** [comment]
wait. I think I found the issue. l will check

**Comment by zhangb1** [comment]
@jharenza @kgaonkar6 

the merged files has been updated in the bucket: 

```
2021-07-21 14:54:03 1073668357 gene-counts-rsem-expected_count-collapsed.rds
2021-07-21 14:28:30 1611312452 gene-expression-rsem-tpm-collapsed.rds
```

md5 also updated

**Comment by kgaonkar6** [comment]
Thanks a lot @zhangb1 !!

@runjin326  can you try to download these files with the updated download-data.sh pointing to v7 s3 bucket? Since you need for fusion_filteering rerun?

**Comment by runjin326** [comment]
@kgaonkar6, @zhangb1, thanks so much! Yes I have downloaded the data and should be able to re-run fusion_filtering now.

**Comment by runjin326** [comment]
Oh sorry forget to mention, @kgaonkar6  - the md5sum did not match. I am guessing that is because they are updated?

**Comment by kgaonkar6** [comment]
Could you remove`gene-counts-rsem-expected_count-collapsed.rds` and `gene-expression-rsem-tpm-collapsed.rds` in your `local data` folder and rerun download-data.sh

**Comment by runjin326** [comment]
Yes. Now it's good!

**Comment by komalsrathi** [comment]
Closing this as we have this data available in OT.
